---
abstract: 'Simple interface to the Google Analytics Data Export API'
author:
  - 'Nick Wellnhofer <wellnhofer@aevum.de>'
generated_by: 'Dist::Zilla version 1.100600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-Analytics
requires:
  Class::Accessor: 0
  ExtUtils::MakeMaker: 6.11
  LWP::UserAgent: 0
  URI: 0
  XML::LibXML: 0
  perl: 5.008
resources:
  repository: http://github.com/nwellnhof/Net-Google-Analytics
version: 0.10000
