---
abstract: 'Simple interface to the Google Analytics Data Export API'
author:
  - 'Nick Wellnhofer <wellnhofer@aevum.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-Analytics
requires:
  Class::Accessor: 0
  LWP::UserAgent: 0
  URI: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  perl: 5.008
resources:
  repository: http://github.com/nwellnhof/Net-Google-Analytics
version: 0.11002
